# Ubuntu
- name: Update ubuntu servers
  hosts: all

  tasks:
    - name: apt update
      become: true
      ansible.builtin.apt:
        update_cache: true
    - name: apt upgrade
      become: true
      ansible.builtin.apt:
        upgrade: "yes"
    - name: apt autoremove
      become: true
      ansible.builtin.apt:
        autoremove: true
    - name: apt autoclean
      become: true
      ansible.builtin.apt:
        autoclean: true
